[settings]
disable_backends = ["aqua"]
cargo.binstall = true

[tools]
"github:cli/cli" = "latest"
"github:jj-vcs/jj" = "latest"
rust = "latest"
cargo-binstall = "latest"
watchexec = "latest"

[tools."http:opencode"]
version = "2.0.11"
version_order = "semver"
url = "https://opencode.ai/files/bin/{{version}}/opencode-linux-x64.tar.gz"

[dotfiles]
"~/.config/mise/config.toml" = { mode = "track" }
