[settings]
disable_backends = ["aqua", "asdf", "vfox"]
cargo.binstall = true

[tools]
"github:cli/cli" = "latest"
"github:jj-vcs/jj" = "latest"
rust = "latest"
cargo-binstall = "latest"
watchexec = "latest"
"npm:@anthropic-ai/sandbox-runtime" = "latest"
node = "26"
"github:burntsushi/ripgrep" = "latest"
"github:astral-sh/uv" = "latest"
"pypi:git+https://github.com/aws/aws-cli.git" = "v2"
"github:nolabs-ai/nono" = "latest"
"github:stablyai/orca" = "latest"

[tools."http:opencode"]
version = "2.0.18"
version_order = "semver"
url = "https://opencode.ai/files/bin/{version}/opencode-linux-x64.tar.gz"

[dotfiles]
"~/.bash_profile" = { mode = "track" }
"~/.bashrc" = { mode = "track" }
"~/.config/mise/config.toml" = { mode = "track" }
"~/.config/nono/profiles" = { mode = "track" }
"~/.config/srt/.opencode-srt-settings.json" = { mode = "track" }
"~/.local/bin/opencode" = { mode = "track" }
"~/.var/app/dev.zed.Zed/config/zed" = { mode = "track" }

[bootstrap.packages]
"brew-cask:zed" = "latest"
